import type { OptimizationResult } from "./types";

export type SiteSource = "measured" | "user_assumption" | "synthetic_fixture" | "provider_observation";
export type SiteEvidence = { id: string; version: number; source: SiteSource; entry_route: "manual" | "sample" | "photo-assisted"; note: string; recorded_at: string | null; instrument: string | null; conditions: string | null; uncertainty: string | null };
export type Site = { id: string; revision: number; name: string; boundary_id: string; boundary_revision: number; length_ft: number | null; width_ft: number | null; canopy_sqft: number | null; included_spaces: string[]; excluded_spaces: string[]; excluded_costs: string[]; evidence: SiteEvidence };
export type SiteAsset = { id: string; revision: number; site_id: string; name: string; kind: string; quantity: number; ownership: "owned" | "proposed" | "unknown"; available: boolean | null; power_basis: "aggregate" | "per_unit"; watts: number | null; component_ids: string[]; footprint_sqft: number | null; evidence: SiteEvidence };
export type SiteOperation = { id: string; revision: number; site_id: string; operation_type: "indoor_leafy_greens"; operation_schema_version: 1; name: string; crop: string | null; cultivar: string | null; method: string | null; start_stage: string | null; end_stage: string | null; product_definition: string; output_unit: "kg_net_marketable_fresh"; horizon_days: number; cycle_days: number; completed_cycles: number; turnover_days: number; idle_days: number; identical_cycles: boolean; starts_per_cycle: number | null; temperature_c: number | null; humidity_pct: number | null; co2_ppm: number | null; ph: number | null; ec_ms_cm: number | null; nutrient_protocol: string | null; protocol_version: number; evidence: SiteEvidence };
export type SiteLoad = { id: string; asset_id: string; asset_revision: number; component_ids: string[]; accounting: "lighting" | "module_other" | "external" | "unpowered"; hours_per_day: number | null; status: "known" | "unknown" | "excluded"; reason: string | null };
export type SiteLighting = { hours_per_day: number; dim_fraction: number; dimmable: boolean; ppfd_full: number | null; ppfd_basis: string | null; min_dli: number | null; min_hours: number; max_hours: number; power_limit_watts: number | null };
export type SiteCostCategory = "electricity" | "water" | "routine_labor" | "consumables" | "maintenance" | "new_equipment" | "setup_labor" | "setup_materials";
export type SiteCost = { id: string; version: number; category: SiteCostCategory; status: "known" | "unknown" | "excluded"; basis: "kwh" | "liter" | "routine_hour" | "setup_hour" | "cycle" | "horizon"; rate: number | null; amount: number | null; component_ids: string[]; asset_ids: string[]; reason: string | null; evidence: SiteEvidence };
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type SiteBenchmark = { id: string; version: number; scenario_id: string; kg_per_cycle: number | null; context: { [key: string]: JsonValue }; uncertainty: { lower: number; upper: number; meaning: string } | null; evidence: SiteEvidence };
export type SiteScenario = { id: string; revision: number; name: string; role: "current" | "alternative"; site_revision: number; operation_revision: number; lighting: SiteLighting; loads: SiteLoad[]; water_liters_day: number | null; routine_labor_hours_cycle: number | null; setup_labor_hours: number | null; costs: SiteCost[]; benchmark: SiteBenchmark | null; change_description: string; evidence: SiteEvidence };
export type SiteMetricKey = "energy_kwh" | "peak_watts" | "output_kg" | "water_liters" | "work_hours" | "new_setup_cash_usd" | "recurring_cash_usd" | "horizon_cash_usd" | "energy_per_kg" | "water_per_kg" | "recurring_cash_per_kg" | "horizon_cash_per_kg" | "lighting_hours" | "dli" | "layout_feasibility";
export type SiteGoal = { id: string; version: number; metric: "output_kg" | "energy_kwh" | "recurring_cash_usd" | "horizon_cash_usd" | "horizon_cash_per_kg"; direction: "minimize" | "maximize"; secondary: { metric: SiteGoal["metric"]; direction: "minimize" | "maximize" }[] };
export type SiteLimit = { id: string; version: number; metric: SiteMetricKey; minimum: number | null; maximum: number | null; unit: string; enabled: boolean; reason: string | null; evidence: SiteEvidence };
export type SiteInputs = { site: Site; assets: SiteAsset[]; operation: SiteOperation; scenarios: SiteScenario[]; goal: SiteGoal; limits: SiteLimit[] };
export type SiteComparisonRequest = SiteInputs & { review: { snapshot_json: string; reviewed_at: string } | null; prior_comparison_id: string | null };
export type SiteMetric = { value: number | null; known_subtotal: number; complete: boolean; unit: string; unknown_line_ids: string[]; excluded_line_ids: string[]; reason: string | null };
export type SiteConstraint = { id: string; metric: SiteMetricKey; status: "pass" | "fail" | "unknown" | "not_evaluated"; value: number | null; known_subtotal: number; minimum: number | null; maximum: number | null; unit: string; reason: string };
export type SiteApplicability = { status: "pass" | "fail" | "unknown"; checks: { path: string; expected: JsonValue; actual: JsonValue; status: "pass" | "fail" | "unknown" }[]; reasons: string[] };
export type SiteFormula = { id: string; metric: string; expression: string; operands: Record<string, JsonValue>; raw_value: number | null; reported_value: number | null; unit: string };
export type SiteLedgerLine = { id: string; category: string; status: "known" | "unknown" | "excluded"; value: number | null; unit: string; quantity: number | null; rate: number | null; component_ids: string[]; reason: string | null };
export type SiteEvaluation = { id: string; created_at: string; scenario_id: string; scenario_revision: number; snapshot: { site: Site; assets: SiteAsset[]; operation: SiteOperation; scenario: SiteScenario; limits: SiteLimit[] }; review_status: "reviewed" | "unreviewed"; provenance: "synthetic_fixture" | "user_defined"; status: "evaluated" | "partial"; metrics: Record<SiteMetricKey, SiteMetric>; feasibility: "pass" | "fail" | "unknown"; constraints: SiteConstraint[]; applicability: SiteApplicability; module_result: OptimizationResult | null; module_status: string; module_included_components: string[]; module_excluded_components: string[]; requested_setting: { hours: number; dim: number; candidate_id: string }; usage_lines: SiteLedgerLine[]; cost_lines: SiteLedgerLine[]; formulas: SiteFormula[]; missing_inputs: string[]; limitations: string[]; explanation: string };
export type SiteRank = { scenario_id: string; evaluation_id: string; eligible: boolean; rank: number | null; value: number | null; reasons: string[] };
export type SiteComparisonPayload = { id: string; created_at: string; parent_id: string | null; accounting_version: "site-scenario-accounting/1.0.0"; benchmark_version: "user-output-benchmark/1.0.0"; lighting_model_version: string; input_snapshot: SiteInputs; input_canonical_json: string; input_sha256: string; review_status: "reviewed" | "unreviewed"; baseline_scenario_id: string; evaluations: SiteEvaluation[]; reused_evaluations: boolean; compatibility: { status: "comparable" | "not_comparable"; reasons: string[] }; ranks: SiteRank[]; preferred_scenario_ids: string[]; comparison_incomplete: boolean; scenario_count: number; feasible_count: number; differences: { scenario_id: string; direction: "scenario_minus_current"; metrics: Record<string, number | null> }[]; explanation: string; limitations: string[] };
export type SiteComparisonArtifact = { schema_version: "site-scenario-comparison/2.0.0"; canonicalization: "python-json-sort-keys-ascii/1"; payload: SiteComparisonPayload; canonical_json: string; sha256: string };
export type SiteVerification = { comparison_id: string; checked_at: string; status: "available" | "unavailable" | "mismatch"; message: string; module_runs: { id: string; available: boolean }[] };

/** Only call when authoring a new, explicitly reviewed benchmark assumption, never on routine edits. */
export function siteBenchmarkContext(inputs: Pick<SiteInputs, "site" | "assets"> & { operation: object }, scenario: Pick<SiteScenario, "loads" | "water_liters_day"> & { lighting: object }): SiteBenchmark["context"] {
  const pick = (value: object, keys: string[]) => Object.fromEntries(keys.map(key => [key, (value as Record<string, JsonValue>)[key]]));
  const operation = Object.fromEntries(Object.entries(inputs.operation).filter(([key]) => !["name", "evidence"].includes(key))) as Record<string, JsonValue>;
  return {
    site: pick(inputs.site, ["id", "revision", "boundary_id", "boundary_revision", "length_ft", "width_ft", "canopy_sqft", "included_spaces", "excluded_spaces"]),
    assets: inputs.assets.map(asset => pick(asset, ["id", "revision", "site_id", "kind", "quantity", "power_basis", "watts", "component_ids", "available"])),
    operation,
    loads: scenario.loads.map(load => pick(load, ["asset_id", "asset_revision", "component_ids", "accounting", "hours_per_day", "status"])),
    lighting: pick(scenario.lighting, ["hours_per_day", "dim_fraction", "dimmable", "ppfd_full", "ppfd_basis"]),
    water_liters_day: scenario.water_liters_day,
  };
}
